
all: 
	gcc -pthread -o main main.c ../Networking/Peer/peer.c ../Networking/Peer/Node/server.c ../Networking/Peer/Node/client.c ../Networking/Peer/Station/server.c ../Networking/Peer/Station/client.c ../Networking/Peer/Station/station.c ../DataStructures/Node/node.c ../DataStructures/Lists/linkedlist.c
